### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dodo49** [Marekkon5/mmlpi#3]
hello, 
i have an error when i start
`pi@Mirror:~ $ cd mmlpi/`
`pi@Mirror:~/mmlpi $ python3 mmlpi.py `
`Traceback (most recent call last):
  File "mmlpi.py", line 1, in <module>
    import mmlpiGUI
  File "/home/pi/mmlpi/mmlpiGUI.py", line 255
    le4 = Label(modsF, text=f'IMPORTANT: Change the path to:\n {p}')
                                                                  ^
SyntaxError: invalid syntax`

**Comment by Marekkon5** [comment]
Hello. I am unable to reproduce the error on clean install. Can you please give me output of your ```python3 --version``` ? Thank you.

**Comment by dodo49** [comment]
i have this
`Python 3.5.3`

**Comment by Marekkon5** [comment]
MMLPi uses f-strings, which require Python 3.6. Which OS are you using? Python 3.6 should be pre-installled on the latest Raspbian.

**Comment by dodo49** [comment]
I am in raspbian 9 : 
`pi@Mirror:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

i will install python 3.6
thk

**Comment by hex007** [comment]
Can the requirement for f-strings be dropped ? Stretch comes pre-installed with 3.5
